# Generated by Django 5.1 on 2025-11-06 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a')], max_length=1, verbose_name='Estado civil')),
                ('es_coleccionista', models.BooleanField(default=False, verbose_name='Es coleccionista')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('contacto', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('años_experiencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Años de experiencia')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='CompraPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_Antiguedades.cliente')),
            ],
            options={
                'verbose_name': 'Compra de Pieza',
                'verbose_name_plural': 'Compras de Piezas',
            },
        ),
        migrations.CreateModel(
            name='PiezaAntiguedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la pieza')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta')),
                ('año_fabricacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(1950)], verbose_name='Año de fabricación')),
                ('estado_conservacion', models.CharField(choices=[('E', 'Excelente'), ('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1, verbose_name='Estado de conservación')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='piezas/', verbose_name='Imagen de la Pieza')),
                ('compradores', models.ManyToManyField(blank=True, related_name='piezas_compradas', through='app_Antiguedades.CompraPieza', to='app_Antiguedades.cliente', verbose_name='Clientes compradores')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas_proveidas', to='app_Antiguedades.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pieza de antigüedad',
                'verbose_name_plural': 'Piezas de antigüedad',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='comprapieza',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_Antiguedades.piezaantiguedad'),
        ),
        migrations.CreateModel(
            name='ClienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de relación')),
                ('tipo_cliente', models.CharField(choices=[('FRECUENTE', 'Cliente Frecuente'), ('OCASIONAL', 'Cliente Ocasional'), ('MAYORISTA', 'Mayorista'), ('COLECCIONISTA', 'Coleccionista')], max_length=50, verbose_name='Tipo de cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Antiguedades.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Antiguedades.proveedor')),
            ],
            options={
                'verbose_name': 'Relación Cliente-Proveedor',
                'verbose_name_plural': 'Relaciones Cliente-Proveedor',
                'unique_together': {('cliente', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='proveedores_favoritos',
            field=models.ManyToManyField(blank=True, related_name='clientes', through='app_Antiguedades.ClienteProveedor', to='app_Antiguedades.proveedor', verbose_name='Proveedores favoritos'),
        ),
        migrations.AlterUniqueTogether(
            name='comprapieza',
            unique_together={('cliente', 'pieza')},
        ),
    ]
